# Generated by Django 4.2 on 2023-04-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
                ('dni', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
            ],
            options={
                'db_table': 'cabeceras',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.FloatField(db_column='sub_total')),
                ('cabecera', models.ForeignKey(db_column='cabecera_id', on_delete=django.db.models.deletion.RESTRICT, to='gestion.cabecera')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.RESTRICT, to='gestion.producto')),
            ],
            options={
                'db_table': 'detalles',
            },
        ),
    ]
